### PR TITLE
Add Test

### PR DESCRIPTION
**Pull request by chaspy**
need to test...!

### CODE REVIEW

**Comment by chaspy** [comment]
@kamontia please add this project in CircleCI.
https://circleci.com/add-projects/gh/kamontia

**Comment by kamontia** [comment]
```
tatsuya@kamontu:~/hobby/git-fixup$ go build
tatsuya@kamontu:~/hobby/git-fixup$ ls
CHANGELOG.md  README.md  commands.go  git-fixup  main.go  script  version.go
tatsuya@kamontu:~/hobby/git-fixup$ bash script/test.sh 
+ TESTDIR=test-git-fixup-25495
+ mkdir -p test-git-fixup-25495
+ cp ./git-fixup test-git-fixup-25495
+ cd test-git-fixup-25495
+ git init
Initialized empty Git repository in /home/tatsuya/hobby/git-fixup/test-git-fixup-25495/.git/
+ touch fileA
+ git add fileA
+ git commit -m 'add fileA'
[master (root-commit) 094b7bb] add fileA
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 fileA
+ touch fileB
+ git add fileB
+ ./git-fixup -f -n 1
*** force update ***
number 1
tatsuya@kamontu:~/hobby/git-fixup$ ls
CHANGELOG.md  README.md  commands.go  git-fixup  main.go  script  test-git-fixup-25495  version.go
tatsuya@kamontu:~/hobby/git-fixup$ cd test-git-fixup-25495/
tatsuya@kamontu:~/hobby/git-fixup/test-git-fixup-25495$ git log --oneline
094b7bb (HEAD -> master) add fileA
tatsuya@kamontu:~/hobby/git-fixup/test-git-fixup-25495$ git diff
tatsuya@kamontu:~/hobby/git-fixup/test-git-fixup-25495$ git diff --cached
diff --git a/fileB b/fileB
new file mode 100644
index 0000000..e69de29
```
CirclCI上でテストは自動ではできない？

**Comment by chaspy** [comment]
@kamontia Thank you for your checking! I'll run on the CircleCI too.

**Comment by chaspy** [comment]
@kamontia 
You can check the result of test on CircleCI.
please click `All checks have passed -> ci/circleci -> Details`

please review and merge.

**Comment by kamontia** [comment]
I checked your request.
If the test is failing on CircleCI, is the result failure?
I wonder that CircleCI check only return code.

**Comment by chaspy** [comment]
I added test for fixup.
@kamontia please review and merge.

**Comment by kamontia** [comment]
Seem to work well

**Pull request merged**
